---
- name: Install Blackbox Exporter
  notify: Blackbox_restart
  block:
    - name: Copy Blackbox Exporter binary
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/Ark4diiV/ansible/main/roles/controlNodeMonitoring/files/binary/blackbox_exporter_amd64
        dest: /usr/local/bin/blackbox_exporter
        mode: '755'

    - name: Make Blackbox config dir
      ansible.builtin.file:
        path: /etc/blackbox
        state: directory
        mode: '755'

    - name: Copy Blackbox config
      ansible.builtin.copy:
        src: configs/blackbox.yml
        dest: /etc/blackbox/blackbox.yml
        mode: '644'

    - name: Copy Blackbox Exporter systemd service
      ansible.builtin.template:
        src: blackbox.service.j2
        dest: /etc/systemd/system/blackbox-exporter.service
        mode: '644'
