---
# Install Node Exporter
- name: Include install_node_exporter.yaml
  ansible.builtin.include_tasks: install_node_exporter.yaml

# Install Wiregurad Exporter
- name: Include install_wireguard_exporter.yaml
  ansible.builtin.include_tasks: install_wireguard_exporter.yaml

# Install Blackbox Exporter
- name: Include install_blackbox_exporter.yaml
  ansible.builtin.include_tasks: install_blackbox_exporter.yaml
  when: vpn_role == "main"

# Install Prometheus
- name: Include install_prometheus.yaml
  ansible.builtin.include_tasks: install_prometheus.yaml
  when: vpn_role == "main"

# Install Grafana
- name: Include install_grafana.yaml
  ansible.builtin.include_tasks: install_grafana.yaml
  when: vpn_role == "main"

# Get certificates
- name: Include install_certs.yaml
  ansible.builtin.include_tasks: install_certs.yaml

# Install Nginx
- name: Include install_nginx.yaml
  ansible.builtin.include_tasks: install_nginx.yaml
  when: vpn_role == "main"

# Clean up after yourself
- name: Include cleaning.yaml
  ansible.builtin.include_tasks: cleaning.yaml
